name: ubuntu-forum-client
version: '0.2'
summary: Ubuntu Community Hub webapp
description: |
  Simple webapp showing discourse.ubuntu.com
base: core24
confinement: strict
grade: devel
compression: lzo

platforms:
  amd64:
  arm64:

apps:
  ubuntu-forum-client:
    extensions: [gnome]
    command: electron/ubuntu-forum-client --disable-gpu --no-sandbox
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
    - network
    - unity7
    - shmem

plugs:
  shmem:
    interface: shared-memory
    private: true

parts:
  forum:
    plugin: nil
    source: ./electron
    build-environment:
      - PATH: "$PATH:$SNAPCRAFT_PART_BUILD/node_modules/.bin"
    override-build: |
      set +u # core20 base does not allow unbound variables !
      # workaround for build.snapcraft.io builds
      # https://bugs.launchpad.net/bugs/1886861
      if [ -n "$http_proxy" ]; then
        export ELECTRON_GET_USE_PROXY=1
        export GLOBAL_AGENT_HTTP_PROXY="${http_proxy}"
        export GLOBAL_AGENT_HTTPS_PROXY="${http_proxy}"
      fi

      npm install
      electron-packager . --overwrite --platform=linux --output=release-build \
          --prune=true --out $SNAPCRAFT_PART_INSTALL/
      mv $SNAPCRAFT_PART_INSTALL/$SNAPCRAFT_PROJECT_NAME-linux-* \
          $SNAPCRAFT_PART_INSTALL/electron
      cp icons/*.png $SNAPCRAFT_PART_INSTALL/
    build-snaps:
      - node/18/stable
    stage-packages:
      - libasound2
      - libnss3
      - libunity9 # for badgeCount in dock
      - libx11-xcb1
      - libxss1
      - libxtst6
  cleanup:
    after: [ forum ]
    plugin: nil
    build-snaps: [ gnome-46-2404 ]
    override-prime: |
      chmod +rx electron
      set -eux
      cd /snap/gnome-46-2404/current
      find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/{} \;
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
